"""empty message

Revision ID: 875133be1033
Revises: d71f48af8608
Create Date: 2023-03-24 06:45:35.469682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "875133be1033"
down_revision = "d71f48af8608"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answer")
    op.drop_table("question")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("subject", sa.VARCHAR(length=200), nullable=False),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("create_date", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "answer",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("question_id", sa.INTEGER(), nullable=True),
        sa.Column("content", sa.TEXT(), nullable=False),
        sa.Column("create_date", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["question.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
