"""empty message

Revision ID: d71f48af8608
Revises: 
Create Date: 2023-03-16 11:53:15.116882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d71f48af8608"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notice", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("author_name", sa.String(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("views_count", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("recommends_count", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("not_recommends_count", sa.Integer(), nullable=False)
        )
        batch_op.add_column(sa.Column("created_date", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("updated_date", sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column("prev_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("next_id", sa.Integer(), nullable=True))
        batch_op.drop_column("recommendsCount")
        batch_op.drop_column("viewsCount")
        batch_op.drop_column("authorName")
        batch_op.drop_column("nextId")
        batch_op.drop_column("notRecommendsCount")
        batch_op.drop_column("prevId")
        batch_op.drop_column("updatedDate")
        batch_op.drop_column("createdDate")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notice", schema=None) as batch_op:
        batch_op.add_column(sa.Column("createdDate", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("updatedDate", sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column("prevId", sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column("notRecommendsCount", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(sa.Column("nextId", sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column("authorName", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.add_column(sa.Column("viewsCount", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("recommendsCount", sa.INTEGER(), nullable=False))
        batch_op.drop_column("next_id")
        batch_op.drop_column("prev_id")
        batch_op.drop_column("updated_date")
        batch_op.drop_column("created_date")
        batch_op.drop_column("not_recommends_count")
        batch_op.drop_column("recommends_count")
        batch_op.drop_column("views_count")
        batch_op.drop_column("author_name")

    # ### end Alembic commands ###
